apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: jupyter
  name: jupyter
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      run: jupyter
  template:
    metadata:
      labels:
        run: jupyter
    spec:
      containers:
      - image: jupyter/minimal-notebook:latest
        imagePullPolicy: Always
        name: jupyter
        ports:
        - containerPort: 8888
          protocol: TCP
        command: ["start-notebook.sh"]
        args: ["--NotebookApp.token='6666f5eb42f60a78577b10f9ca3ae3ce'"]
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
