
apiVersion: v1
kind: Service
metadata:
  labels:
    run: jupyter
  name: jupyter
  namespace: default
spec:
  ports:
  - nodePort: 31111
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    run: jupyter
  sessionAffinity: None
  type: NodePort # or LoadBalancer
