apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: nvidia-jupyter
  name: nvidia-jupyter
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      run: nvidia-jupyter
  template:
    metadata:
      labels:
        run: nvidia-jupyter
    spec:
      containers:
      - image: tensorflow/tensorflow:latest-gpu-py3-jupyter
        imagePullPolicy: Always
        name: nvidia-jupyter
        # two lines below start tensorboard running on tcp6006
        # if commented out, jupyter notebook is started instead on tcp8888
        #command: ["/bin/sh", "-c"]
        #args: ["export LD_LIBRARY_PATH='/usr/local/nvidia/lib64:/usr/local/nvidia/bin'; tensorboard --bind_all --logdir /tmp/DeepLearning_21_Examples-master/chapter_01"]
        ports:
        - containerPort: 8888 # or 6006
          protocol: TCP
        resources:
          # !!! to install NVIDIA drivers inside and enable GPU
          # this have to be defined !!!
          limits:
            nvidia.com/gpu: 1
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
